/* eslint-disable */
// AUTO-GENERATED by tools/cell-manifest — DO NOT EDIT BY HAND.
// Source: gocell/corecells/**
// Regenerate: pnpm cell-manifest (CI guards via git diff --exit-code)
import type { CellManifest } from './types'

export const CELL_MANIFEST: CellManifest = {
  "cells": [
    {
      "id": "accesscore",
      "name": "AccessCore",
      "domain": "Access",
      "type": "core",
      "consistencyLevel": "L3",
      "lifecycle": "asset",
      "durabilityMode": "durable",
      "owner": {
        "team": "platform",
        "role": "cell-owner"
      },
      "goStructName": "AccessCore",
      "schemaPrimary": "cell_access_core",
      "requires": [
        "postgres",
        "redis"
      ],
      "l0Dependencies": [],
      "smokeTests": [
        "smoke.accesscore.startup"
      ],
      "slices": [
        {
          "id": "authorizationdecide",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.auth.decide.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.authorizationdecide.service"
          ],
          "contractTests": [
            "contract.http.auth.decide.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "configreceive",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L3",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.config.entry-upserted.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.config.entry-deleted.v1",
              "role": "subscribe"
            },
            {
              "contract": "http.config.internal.get.v1",
              "role": "call"
            }
          ],
          "unitTests": [
            "unit.configreceive.service"
          ],
          "contractTests": [
            "contract.event.config.entry-upserted.v1.subscribe",
            "contract.event.config.entry-deleted.v1.subscribe",
            "contract.http.config.internal.get.v1.call"
          ],
          "waivers": []
        },
        {
          "id": "identitymanage",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.user.created.v1",
              "role": "publish"
            },
            {
              "contract": "event.user.locked.v1",
              "role": "publish"
            },
            {
              "contract": "event.user.deleted.v1",
              "role": "publish"
            },
            {
              "contract": "event.user.updated.v1",
              "role": "publish"
            },
            {
              "contract": "event.user.unlocked.v1",
              "role": "publish"
            },
            {
              "contract": "http.auth.user.create.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.user.get.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.user.update.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.user.patch.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.user.delete.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.user.lock.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.user.unlock.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.user.change-password.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.identitymanage.service"
          ],
          "contractTests": [
            "contract.event.user.created.v1.publish",
            "contract.event.user.locked.v1.publish",
            "contract.event.user.deleted.v1.publish",
            "contract.event.user.updated.v1.publish",
            "contract.event.user.unlocked.v1.publish",
            "contract.http.auth.user.create.v1.serve",
            "contract.http.auth.user.get.v1.serve",
            "contract.http.auth.user.update.v1.serve",
            "contract.http.auth.user.patch.v1.serve",
            "contract.http.auth.user.delete.v1.serve",
            "contract.http.auth.user.lock.v1.serve",
            "contract.http.auth.user.unlock.v1.serve",
            "contract.http.auth.user.change-password.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "policymanage",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.policy.updated.v1",
              "role": "publish"
            },
            {
              "contract": "http.policy.create.v1",
              "role": "serve"
            },
            {
              "contract": "http.policy.get.v1",
              "role": "serve"
            },
            {
              "contract": "http.policy.update.v1",
              "role": "serve"
            },
            {
              "contract": "http.policy.delete.v1",
              "role": "serve"
            },
            {
              "contract": "http.policy.list.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.policymanage.service"
          ],
          "contractTests": [
            "contract.event.policy.updated.v1.publish",
            "contract.http.policy.create.v1.serve",
            "contract.http.policy.get.v1.serve",
            "contract.http.policy.update.v1.serve",
            "contract.http.policy.delete.v1.serve",
            "contract.http.policy.list.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "rbacassign",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.auth.role.assign.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.role.revoke.v1",
              "role": "serve"
            },
            {
              "contract": "event.role.assigned.v1",
              "role": "publish"
            },
            {
              "contract": "event.role.revoked.v1",
              "role": "publish"
            }
          ],
          "unitTests": [
            "unit.rbacassign.service"
          ],
          "contractTests": [
            "contract.http.auth.role.assign.v1.serve",
            "contract.http.auth.role.revoke.v1.serve",
            "contract.event.role.assigned.v1.publish",
            "contract.event.role.revoked.v1.publish"
          ],
          "waivers": []
        },
        {
          "id": "rbaccheck",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.auth.role.list.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.role.check.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.rbaccheck.service"
          ],
          "contractTests": [
            "contract.http.auth.role.list.v1.serve",
            "contract.http.auth.role.check.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "sessionlogin",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.auth.login.v1",
              "role": "serve"
            },
            {
              "contract": "event.session.created.v1",
              "role": "publish"
            },
            {
              "contract": "event.user.locked.v1",
              "role": "publish"
            },
            {
              "contract": "event.user.unlocked.v1",
              "role": "publish"
            },
            {
              "contract": "http.config.get.v1",
              "role": "call"
            }
          ],
          "unitTests": [
            "unit.sessionlogin.service"
          ],
          "contractTests": [
            "contract.http.auth.login.v1.serve",
            "contract.event.session.created.v1.publish",
            "contract.event.user.locked.v1.publish",
            "contract.event.user.unlocked.v1.publish"
          ],
          "waivers": [
            {
              "contract": "http.config.get.v1",
              "owner": "platform-team",
              "reason": "只读配置调用，集成测试已覆盖；waiver 由 #1467 续期解阻塞 develop CI，补测试还债见 #1472",
              "expiresAt": "2026-09-01"
            }
          ]
        },
        {
          "id": "sessionlogout",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.auth.session.delete.v1",
              "role": "serve"
            },
            {
              "contract": "event.session.revoked.v1",
              "role": "publish"
            },
            {
              "contract": "event.role.assigned.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.role.revoked.v1",
              "role": "subscribe"
            }
          ],
          "unitTests": [
            "unit.sessionlogout.service"
          ],
          "contractTests": [
            "contract.http.auth.session.delete.v1.serve",
            "contract.event.session.revoked.v1.publish"
          ],
          "waivers": [
            {
              "contract": "event.role.assigned.v1",
              "owner": "platform-team",
              "reason": "consumer contract test tracked under S8-FOLLOWUP; handler tested by consumer_test.go",
              "expiresAt": "2026-07-01"
            },
            {
              "contract": "event.role.revoked.v1",
              "owner": "platform-team",
              "reason": "consumer contract test tracked under S8-FOLLOWUP; handler tested by consumer_test.go",
              "expiresAt": "2026-07-01"
            }
          ]
        },
        {
          "id": "sessionrefresh",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L1",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.auth.refresh.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.sessionrefresh.service"
          ],
          "contractTests": [
            "contract.http.auth.refresh.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "sessionvalidate",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [],
          "unitTests": [
            "unit.sessionvalidate.service"
          ],
          "contractTests": [],
          "waivers": []
        },
        {
          "id": "sessionverifyrpc",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L0",
          "lifecycle": "experimental",
          "contractUsages": [
            {
              "contract": "grpc.auth.session.verify.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.sessionverifyrpc.server"
          ],
          "contractTests": [
            "contract.grpc.auth.session.verify.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "setup",
          "belongsToCell": "accesscore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.auth.setup.status.v1",
              "role": "serve"
            },
            {
              "contract": "http.auth.setup.admin.v1",
              "role": "serve"
            },
            {
              "contract": "event.user.created.v1",
              "role": "publish"
            },
            {
              "contract": "event.auth.bootstrap-failed.v1",
              "role": "publish"
            }
          ],
          "unitTests": [
            "unit.setup.service"
          ],
          "contractTests": [
            "contract.http.auth.setup.status.v1.serve",
            "contract.http.auth.setup.admin.v1.serve",
            "contract.event.user.created.v1.publish",
            "contract.event.auth.bootstrap-failed.v1.publish"
          ],
          "waivers": []
        }
      ],
      "produces": [
        {
          "contract": "event.auth.bootstrap-failed.v1",
          "role": "publish"
        },
        {
          "contract": "event.policy.updated.v1",
          "role": "publish"
        },
        {
          "contract": "event.role.assigned.v1",
          "role": "publish"
        },
        {
          "contract": "event.role.revoked.v1",
          "role": "publish"
        },
        {
          "contract": "event.session.created.v1",
          "role": "publish"
        },
        {
          "contract": "event.session.revoked.v1",
          "role": "publish"
        },
        {
          "contract": "event.user.created.v1",
          "role": "publish"
        },
        {
          "contract": "event.user.deleted.v1",
          "role": "publish"
        },
        {
          "contract": "event.user.locked.v1",
          "role": "publish"
        },
        {
          "contract": "event.user.unlocked.v1",
          "role": "publish"
        },
        {
          "contract": "event.user.updated.v1",
          "role": "publish"
        },
        {
          "contract": "grpc.auth.session.verify.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.decide.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.login.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.refresh.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.role.assign.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.role.check.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.role.list.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.role.revoke.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.session.delete.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.setup.admin.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.setup.status.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.change-password.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.create.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.delete.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.get.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.lock.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.patch.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.unlock.v1",
          "role": "serve"
        },
        {
          "contract": "http.auth.user.update.v1",
          "role": "serve"
        },
        {
          "contract": "http.policy.create.v1",
          "role": "serve"
        },
        {
          "contract": "http.policy.delete.v1",
          "role": "serve"
        },
        {
          "contract": "http.policy.get.v1",
          "role": "serve"
        },
        {
          "contract": "http.policy.list.v1",
          "role": "serve"
        },
        {
          "contract": "http.policy.update.v1",
          "role": "serve"
        }
      ],
      "consumes": [
        {
          "contract": "event.config.entry-deleted.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.config.entry-upserted.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.role.assigned.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.role.revoked.v1",
          "role": "subscribe"
        },
        {
          "contract": "http.config.get.v1",
          "role": "call"
        },
        {
          "contract": "http.config.internal.get.v1",
          "role": "call"
        }
      ],
      "dependsOnCells": [
        "configcore"
      ],
      "requiredByCells": [
        "auditcore"
      ]
    },
    {
      "id": "auditcore",
      "name": "AuditCore",
      "domain": "Audit",
      "type": "core",
      "consistencyLevel": "L2",
      "lifecycle": "asset",
      "durabilityMode": "durable",
      "owner": {
        "team": "platform",
        "role": "cell-owner"
      },
      "goStructName": "AuditCore",
      "schemaPrimary": "cell_audit_core",
      "requires": [
        "postgres"
      ],
      "l0Dependencies": [],
      "smokeTests": [
        "smoke.auditcore.startup"
      ],
      "slices": [
        {
          "id": "auditappendbootstrap",
          "belongsToCell": "auditcore",
          "consistencyLevel": "L1",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.auth.bootstrap-failed.v1",
              "role": "subscribe"
            }
          ],
          "unitTests": [
            "unit.auditappendbootstrap.service"
          ],
          "contractTests": [
            "contract.event.auth.bootstrap-failed.v1.subscribe"
          ],
          "waivers": []
        },
        {
          "id": "auditappendconfig",
          "belongsToCell": "auditcore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.audit.appended.v1",
              "role": "publish"
            },
            {
              "contract": "event.config.entry-upserted.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.config.entry-deleted.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.config.version-published.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.config.rollback.v1",
              "role": "subscribe"
            }
          ],
          "unitTests": [
            "unit.auditappendconfig.service"
          ],
          "contractTests": [
            "contract.event.audit.appended.v1.publish",
            "contract.event.config.entry-upserted.v1.subscribe",
            "contract.event.config.entry-deleted.v1.subscribe",
            "contract.event.config.version-published.v1.subscribe",
            "contract.event.config.rollback.v1.subscribe"
          ],
          "waivers": []
        },
        {
          "id": "auditappendrole",
          "belongsToCell": "auditcore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.audit.appended.v1",
              "role": "publish"
            },
            {
              "contract": "event.role.assigned.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.role.revoked.v1",
              "role": "subscribe"
            }
          ],
          "unitTests": [
            "unit.auditappendrole.service"
          ],
          "contractTests": [
            "contract.event.audit.appended.v1.publish",
            "contract.event.role.assigned.v1.subscribe",
            "contract.event.role.revoked.v1.subscribe"
          ],
          "waivers": []
        },
        {
          "id": "auditappendsession",
          "belongsToCell": "auditcore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.audit.appended.v1",
              "role": "publish"
            },
            {
              "contract": "event.session.created.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.session.revoked.v1",
              "role": "subscribe"
            }
          ],
          "unitTests": [
            "unit.auditappendsession.service"
          ],
          "contractTests": [
            "contract.event.audit.appended.v1.publish",
            "contract.event.session.created.v1.subscribe",
            "contract.event.session.revoked.v1.subscribe"
          ],
          "waivers": []
        },
        {
          "id": "auditappenduser",
          "belongsToCell": "auditcore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.audit.appended.v1",
              "role": "publish"
            },
            {
              "contract": "event.user.created.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.user.locked.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.user.unlocked.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.user.updated.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.user.deleted.v1",
              "role": "subscribe"
            }
          ],
          "unitTests": [
            "unit.auditappenduser.service"
          ],
          "contractTests": [
            "contract.event.audit.appended.v1.publish",
            "contract.event.user.created.v1.subscribe",
            "contract.event.user.locked.v1.subscribe",
            "contract.event.user.unlocked.v1.subscribe",
            "contract.event.user.updated.v1.subscribe",
            "contract.event.user.deleted.v1.subscribe"
          ],
          "waivers": []
        },
        {
          "id": "auditquery",
          "belongsToCell": "auditcore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.audit.list.v1",
              "role": "serve"
            },
            {
              "contract": "http.audit.get.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.auditquery.service"
          ],
          "contractTests": [
            "contract.http.audit.list.v1.serve",
            "contract.http.audit.get.v1.serve"
          ],
          "waivers": []
        }
      ],
      "produces": [
        {
          "contract": "event.audit.appended.v1",
          "role": "publish"
        },
        {
          "contract": "http.audit.get.v1",
          "role": "serve"
        },
        {
          "contract": "http.audit.list.v1",
          "role": "serve"
        }
      ],
      "consumes": [
        {
          "contract": "event.auth.bootstrap-failed.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.config.entry-deleted.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.config.entry-upserted.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.config.rollback.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.config.version-published.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.role.assigned.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.role.revoked.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.session.created.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.session.revoked.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.user.created.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.user.deleted.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.user.locked.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.user.unlocked.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.user.updated.v1",
          "role": "subscribe"
        }
      ],
      "dependsOnCells": [
        "accesscore",
        "configcore"
      ],
      "requiredByCells": []
    },
    {
      "id": "configcore",
      "name": "ConfigCore",
      "domain": "Config",
      "type": "core",
      "consistencyLevel": "L3",
      "lifecycle": "asset",
      "durabilityMode": "durable",
      "owner": {
        "team": "platform",
        "role": "cell-owner"
      },
      "goStructName": "ConfigCore",
      "schemaPrimary": "cell_config_core",
      "requires": [
        "postgres"
      ],
      "l0Dependencies": [],
      "smokeTests": [
        "smoke.configcore.startup"
      ],
      "slices": [
        {
          "id": "configpublish",
          "belongsToCell": "configcore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.config.publish.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.rollback.v1",
              "role": "serve"
            },
            {
              "contract": "event.config.entry-upserted.v1",
              "role": "publish"
            },
            {
              "contract": "event.config.version-published.v1",
              "role": "publish"
            },
            {
              "contract": "event.config.rollback.v1",
              "role": "publish"
            }
          ],
          "unitTests": [
            "unit.configpublish.service"
          ],
          "contractTests": [
            "contract.http.config.publish.v1.serve",
            "contract.http.config.rollback.v1.serve",
            "contract.event.config.entry-upserted.v1.publish",
            "contract.event.config.version-published.v1.publish",
            "contract.event.config.rollback.v1.publish"
          ],
          "waivers": []
        },
        {
          "id": "configread",
          "belongsToCell": "configcore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.config.get.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.list.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.configread.service"
          ],
          "contractTests": [
            "contract.http.config.get.v1.serve",
            "contract.http.config.list.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "configreadinternal",
          "belongsToCell": "configcore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.config.internal.get.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.configreadinternal.service"
          ],
          "contractTests": [
            "contract.http.config.internal.get.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "configsubscribe",
          "belongsToCell": "configcore",
          "consistencyLevel": "L3",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "event.config.entry-upserted.v1",
              "role": "subscribe"
            },
            {
              "contract": "event.config.entry-deleted.v1",
              "role": "subscribe"
            }
          ],
          "unitTests": [
            "unit.configsubscribe.service"
          ],
          "contractTests": [
            "contract.event.config.entry-upserted.v1.subscribe",
            "contract.event.config.entry-deleted.v1.subscribe"
          ],
          "waivers": []
        },
        {
          "id": "configwrite",
          "belongsToCell": "configcore",
          "consistencyLevel": "L2",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.config.write.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.update.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.delete.v1",
              "role": "serve"
            },
            {
              "contract": "event.config.entry-upserted.v1",
              "role": "publish"
            },
            {
              "contract": "event.config.entry-deleted.v1",
              "role": "publish"
            }
          ],
          "unitTests": [
            "unit.configwrite.service"
          ],
          "contractTests": [
            "contract.http.config.write.v1.serve",
            "contract.http.config.update.v1.serve",
            "contract.http.config.delete.v1.serve",
            "contract.event.config.entry-upserted.v1.publish",
            "contract.event.config.entry-deleted.v1.publish"
          ],
          "waivers": []
        },
        {
          "id": "featureflag",
          "belongsToCell": "configcore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.config.flags.list.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.flags.get.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.flags.evaluate.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.featureflag.service"
          ],
          "contractTests": [
            "contract.http.config.flags.list.v1.serve",
            "contract.http.config.flags.get.v1.serve",
            "contract.http.config.flags.evaluate.v1.serve"
          ],
          "waivers": []
        },
        {
          "id": "flagwrite",
          "belongsToCell": "configcore",
          "consistencyLevel": "L1",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.config.flags.create.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.flags.update.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.flags.toggle.v1",
              "role": "serve"
            },
            {
              "contract": "http.config.flags.delete.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.flagwrite.service"
          ],
          "contractTests": [
            "contract.http.config.flags.create.v1.serve",
            "contract.http.config.flags.update.v1.serve",
            "contract.http.config.flags.toggle.v1.serve",
            "contract.http.config.flags.delete.v1.serve"
          ],
          "waivers": []
        }
      ],
      "produces": [
        {
          "contract": "event.config.entry-deleted.v1",
          "role": "publish"
        },
        {
          "contract": "event.config.entry-upserted.v1",
          "role": "publish"
        },
        {
          "contract": "event.config.rollback.v1",
          "role": "publish"
        },
        {
          "contract": "event.config.version-published.v1",
          "role": "publish"
        },
        {
          "contract": "http.config.delete.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.flags.create.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.flags.delete.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.flags.evaluate.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.flags.get.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.flags.list.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.flags.toggle.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.flags.update.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.get.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.internal.get.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.list.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.publish.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.rollback.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.update.v1",
          "role": "serve"
        },
        {
          "contract": "http.config.write.v1",
          "role": "serve"
        }
      ],
      "consumes": [
        {
          "contract": "event.config.entry-deleted.v1",
          "role": "subscribe"
        },
        {
          "contract": "event.config.entry-upserted.v1",
          "role": "subscribe"
        }
      ],
      "dependsOnCells": [],
      "requiredByCells": [
        "accesscore",
        "auditcore"
      ]
    },
    {
      "id": "syscore",
      "name": "SysCore",
      "domain": "Sys",
      "type": "support",
      "consistencyLevel": "L1",
      "lifecycle": "asset",
      "durabilityMode": "durable",
      "owner": {
        "team": "platform",
        "role": "cell-owner"
      },
      "goStructName": "SysCore",
      "schemaPrimary": "cell_syscore",
      "requires": [],
      "l0Dependencies": [],
      "smokeTests": [
        "smoke.syscore.startup"
      ],
      "slices": [
        {
          "id": "healthread",
          "belongsToCell": "syscore",
          "consistencyLevel": "L0",
          "lifecycle": "asset",
          "contractUsages": [
            {
              "contract": "http.admin.health.cells.v1",
              "role": "serve"
            }
          ],
          "unitTests": [
            "unit.healthread.service"
          ],
          "contractTests": [
            "contract.http.admin.health.cells.v1.serve"
          ],
          "waivers": []
        }
      ],
      "produces": [
        {
          "contract": "http.admin.health.cells.v1",
          "role": "serve"
        }
      ],
      "consumes": [],
      "dependsOnCells": [],
      "requiredByCells": []
    }
  ],
  "generatedFrom": "gocell/corecells/**/{cell.yaml,slices/*/slice.yaml}"
}
