import { createHash, randomUUID } from 'node:crypto'
import type { DomainHandler, Scenario } from '../scenario'
import type { createResourceDemo, ResourceImport } from '../policies/resources'
import type { createAdmissionDemo } from './admission'
import { createPages, createReceipts, error, operation } from '../http'
import { closed, count, enumeration, identifier, uuid } from '../../src/services/decode'
import {
  decodeSoftwareDefinition,
  type SoftwareDefinition,
} from '../../src/features/policies/clients/software-definition'
import type { ImportJob, ImportResolution } from '../../src/features/software/clients/imports'
import { candidate } from './catalog'
const hash = (value: string | Uint8Array) => [...createHash('sha256').update(value).digest()]
/** Synthetic upstream fixtures are resolved here, never generated by a browser component. */
function externalPackage(
  source: SoftwareDefinition['source'],
  ecosystem: 'winget' | 'brew',
  architecture: 'x86_64' | 'aarch64',
) {
  const windows = ecosystem === 'winget',
    platform = windows ? 'windows' : 'macos'
  const packageId = windows ? 'Example.Browser' : 'example-editor',
    version = windows ? '128.0' : '1.0'
  const payload = new TextEncoder().encode(
    `SYNTHETIC ${ecosystem} ${packageId} ${version} ${architecture}\n`,
  )
  const detector = new TextEncoder().encode(windows ? 'exit 1\n' : '#!/bin/sh\nexit 1\n')
  const file = (reference: string, bytes: Uint8Array) => ({
    reference,
    origin: null,
    length: bytes.length,
    sha256: hash(bytes),
  })
  const invocation = {
    runAs: windows ? 'system' : 'logged_in_user',
    arguments: [],
    environment: {},
    timeoutSeconds: 3600,
    outputBytes: 16384,
    exitCodes: { success: [0], reboot: [] },
  }
  const install = {
    ...invocation,
    arguments: windows
      ? ['install', '--id', packageId, '--version', version, '--exact']
      : ['install', `${packageId}@${version}`],
  }
  const definition = decodeSoftwareDefinition({
    source,
    package: packageId,
    version,
    provenance: { kind: 'private' },
    signatures: [],
    export: { kind: 'disabled' },
    artifacts: { package: file('package', payload), detect: file('detect', detector) },
    behavior: {
      kind: ecosystem,
      installer: 'package',
      scope: windows ? 'system' : 'user',
      install,
      upgradeInvocation: install,
      upgrade: 'in_place',
      uninstall: {
        installer: 'package',
        invocation: {
          ...invocation,
          arguments: windows
            ? ['uninstall', '--id', packageId, '--exact']
            : ['uninstall', `${packageId}@${version}`],
        },
      },
      detect: {
        kind: 'script',
        command: {
          interpreter: windows ? 'power_shell7' : 'posix_sh',
          entry: 'detect',
          invocation,
        },
      },
    },
    reboot: 'report',
    downgrade: 'deny',
    dependencies: [],
  })
  return {
    platform,
    package: packageId,
    version,
    definition,
    files: [
      { platform, architecture, variant: 'main', reference: 'package', bytes: payload },
      { platform, architecture, variant: 'main', reference: 'detect', bytes: detector },
    ],
  } as const
}
export function createImportsDemo(
  resources: ReturnType<typeof createResourceDemo>,
  admission: ReturnType<typeof createAdmissionDemo>,
) {
  const resolutions = new Map<
    string,
    { view: ImportResolution; material: ReturnType<typeof externalPackage> }
  >()
  const jobs = new Map<string, { view: ImportJob; input: ResourceImport }>(),
    pages = createPages(),
    receipts = createReceipts()
  function settle(job: { view: ImportJob; input: ResourceImport }, scenario: Scenario) {
    const known = resources.importReceipt(job.input.operation)
    if (known !== null) {
      job.view.status = 'completed'
      job.view.resourceRevision = known
      job.view.failure = null
      return
    }
    if (!admission.sourceAllowed(job.view.resolution.source)) {
      job.view.status = 'failed'
      job.view.failure = 'source_withdrawn'
      return
    }
    if (scenario === 'partial') {
      job.view.status = 'failed'
      job.view.failure = 'content_invalid'
      return
    }
    const receipt = resources.importVersion(job.input)
    if ('failure' in receipt) {
      job.view.status = 'failed'
      job.view.failure = receipt.failure!
      return
    }
    job.view.status = scenario === 'unknown' ? 'unknown' : 'completed'
    job.view.resourceRevision = scenario === 'unknown' ? null : receipt.revision
    job.view.failure = null
  }
  function advance(scenario: Scenario) {
    for (const job of jobs.values())
      if (job.view.status === 'pending') {
        settle(job, scenario)
        job.view.revision++
      }
  }
  const handle: DomainHandler = (request, scenario) => {
    if (
      !/^\/api\/v1\/mdm-candidate\/software\/(import-resolutions|imports)(?:\/|$)/.test(
        request.path,
      )
    )
      return
    if (scenario === 'denied') return error('permission_denied', 403)
    try {
      if (request.path.endsWith('/import-resolutions') && request.method === 'GET') {
        const query = request.query,
          source = admission.source(
            identifier(query.get('source')),
            identifier(query.get('revision')),
          )
        if (!source || source.admission.state !== 'approved' || source.source.kind === 'private')
          return error('operation_conflict')
        const architecture = enumeration(query.get('architecture'), ['x86_64', 'aarch64'] as const)
        const material = externalPackage(source.snapshot, source.source.kind, architecture)
        if (
          query.get('package') !== material.package ||
          query.get('version') !== material.version ||
          query.get('platform') !== material.platform
        )
          return error('operation_not_found', 404)
        const view: ImportResolution = {
          id: randomUUID(),
          source: source.snapshot,
          ecosystem: source.source.kind,
          package: material.package,
          version: material.version,
          platform: material.platform,
          architecture,
          definitionDigest: hash(JSON.stringify(material.definition)),
          expiresAt: Math.floor(Date.now() / 1000) + 900,
        }
        resolutions.set(view.id, { view, material })
        return candidate({ resolution: view })
      }
      const match = /^\/api\/v1\/mdm-candidate\/software\/imports(?:\/([^/]+))?$/.exec(request.path)
      if (!match) return error('malformed_request', 400)
      if (!match[1] && request.method === 'GET') {
        if (scenario !== 'empty') advance(scenario)
        return candidate(
          pages.page(
            request.path,
            scenario === 'empty' ? [] : [...jobs.values()].map((j) => j.view),
            request.query,
          ),
        )
      }
      const id = uuid(match[1]),
        current = jobs.get(id)
      if (request.method === 'GET') {
        if (current?.view.status === 'pending') advance(scenario)
        return current
          ? candidate({ job: structuredClone(current.view) })
          : error('operation_not_found', 404)
      }
      if (request.method !== 'POST') return
      const op = operation(request.body)
      return receipts.write(request, op.operationId, () => {
        if ((current?.view.revision ?? 0) !== op.expectedRevision)
          return error('operation_conflict')
        const input = closed(
          op.input,
          typeof op.input === 'object' &&
            op.input !== null &&
            'action' in op.input &&
            op.input.action === 'start'
            ? ['action', 'resolution', 'resource', 'version', 'expectedResourceRevision']
            : ['action'],
        )
        const action = enumeration(input['action'], ['start', 'cancel', 'reconcile'] as const)
        if (action === 'start') {
          const selected = resolutions.get(uuid(input['resolution']))
          if (
            current ||
            !selected ||
            selected.view.expiresAt <= Math.floor(Date.now() / 1000) ||
            !admission.sourceAllowed(selected.view.source)
          )
            return error('operation_conflict')
          const resource = identifier(input['resource']),
            version = identifier(input['version']),
            expectedRevision = count(input['expectedResourceRevision'])
          if ((resources.read(resource)?.revision ?? 0) !== expectedRevision)
            return error('operation_conflict')
          const view: ImportJob = {
            id,
            revision: 1,
            operation: op.operationId,
            resolution: structuredClone(selected.view),
            resource,
            version,
            status: 'pending',
            failure: null,
            resourceRevision: null,
          }
          const job = {
            view,
            input: {
              operation: id,
              actor: request.actor.principalId,
              resource,
              version,
              expectedRevision,
              variants: [
                {
                  platform: selected.view.platform,
                  architecture: selected.view.architecture,
                  key: 'main',
                  declaration: {
                    kind: 'software' as const,
                    definition: selected.material.definition,
                  },
                },
              ],
              files: [...selected.material.files],
            },
          }
          jobs.set(id, job)
          return candidate({ job: structuredClone(view) }, 202)
        }
        if (!current) return error('operation_not_found', 404)
        if (action === 'cancel') {
          if (current.view.status !== 'pending') return error('operation_conflict')
          current.view.status = 'cancelled'
        } else {
          if (current.view.status !== 'unknown') return error('operation_conflict')
          settle(current, scenario)
        }
        current.view.revision++
        current.view.operation = op.operationId
        return candidate({ job: structuredClone(current.view) })
      })
    } catch {
      return error('malformed_request', 400)
    }
  }
  return {
    handle,
    advance,
    reset() {
      resolutions.clear()
      jobs.clear()
      pages.reset()
      receipts.reset()
    },
  }
}
