proxy_http_version 1.1;
proxy_set_header Host $proxy_host;
proxy_set_header X-Tenant-ID $rss_tenant_header;
proxy_set_header Forwarded "";
proxy_set_header X-Original-URI "";
proxy_set_header X-Original-URL "";
proxy_set_header X-Rewrite-URL "";
proxy_set_header X-Forwarded-By "";
proxy_set_header X-Forwarded-Host "";
proxy_set_header X-Forwarded-Path "";
proxy_set_header X-Forwarded-Prefix "";
proxy_set_header X-Forwarded-Port "";
proxy_set_header X-Forwarded-Server "";
proxy_set_header X-Forwarded-Uri "";
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_next_upstream off;
proxy_connect_timeout 2s;
proxy_send_timeout 60s;
proxy_read_timeout 60s;
proxy_no_cache 1;
proxy_cache_bypass 1;
